### ISSUE TITLE
Add Librewolf to Browsers

### ISSUE THREAD

**Issue by IAmGCS** [techlore/channel-content#17]
Librewolf is an open-source, tweaked version of Firefox that comes hardening pre-configured. Detailed explanation can be found in [their site](https://librewolf-community.gitlab.io/).

**Comment by techlore-official** [comment]
We're still hesitant to recommend people to tools like Librewolf, at least in a video like this. This is mostly due to:
A) Longevity of the projects and ensuring our content doesn't become quickly outdated. There have been plenty of Firefox forks in the past and many are no longer trusted or no longer exist unfortunately. 
B) There's no librewolf for mobile, and this isn't a video about browsers where we can really talk to people about pros/cons. So sticking to tools with more of a common understanding and community around them may help alleviate this problem. 

I'm not 100% on this, so please get back with any thoughts for why this reasoning may not be valid in your eyes. My fear is if we quickly reference librewolf it would lead to more questions than answers, so it's not the right place to talk about it.

**Comment by shaurya-007** [comment]
I think you should refer your browser video here (in this video) and just leave it at that.

**Comment by IAmGCS** [comment]
> We're still hesitant to recommend people to tools like Librewolf, at least in a video like this. This is mostly due to:
> A) Longevity of the projects and ensuring our content doesn't become quickly outdated. There have been plenty of Firefox forks in the past and many are no longer trusted or no longer exist unfortunately.
> B) There's no librewolf for mobile, and this isn't a video about browsers where we can really talk to people about pros/cons. So sticking to tools with more of a common understanding and community around them may help alleviate this problem.
> 
> I'm not 100% on this, so please get back with any thoughts for why this reasoning may not be valid in your eyes. My fear is if we quickly reference librewolf it would lead to more questions than answers, so it's not the right place to talk about it.

A) Librewolf since it's been released has been kept up to date always with the newest ff version. The project also recieved attention thanks to other Linux youtubers recommending it. Because of these 2 reasons I think Librewolf will continue getting updated.
B) I think Librewolf being not on mobile isn't that much of an issue since most privacy-minded people doesn't recommend directly using normal ff on mobile but rather an alternative like Ddg, Bromite, etc. So browser in mobile and desktop differentiate anyways.

It's true that people might get a little bit confused but if we compare installing Librewolf to hardening your browser, the process is much simpler and stable. As you know too when ff 89.0 came out it broke/changed some of the configs but people who used Librewolf didn't need to re-harden or tweak the configs again. So Librewolf had this advantage on a recent event.

**Comment by techlore-official** [comment]
4 days later and I'm still mixed on this one. 

Going to write this as a note and will make a final decision once I see how the script comes out and how nicely a mention would fit into the video.

Thanks for the notes everyone!
